services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
      - 5433:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  postgres-data: