version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: laser
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: laser
      ME_CONFIG_MONGODB_URL: mongodb+srv://slava187115:GYUDuSQYI6GFkmVk@cluster0.gi5tyfq.mongodb.net/
      ME_CONFIG_BASICAUTH: null

volumes:
  mongo-data:
